var PayloadType = {
	INFOREQUEST : 10,
	INFORESPONSE : 20,
	CONTROLREQUEST : 30,
	CONTROLRESPONSE : 40,
	CONFIGREQUEST : 50,
	CONFIGRESPONSE : 60,
	HEARTBEATREQUEST : 70,
	HEARTBEAT : 80
};

module.exports = PayloadType;
